### ISSUE TITLE
PHP Compile Error

### ISSUE THREAD

**Issue by azerturk** [gromver/yii2-platform-basic#1]
PHP Compile Error – yii\base\ErrorException

Cannot use yii\web\Request as Request because the name is already in use

C:\wamp\www\basic\vendor\gromver\yii2-platform-basic\components\MenuManager.php at line 22

**Comment by gromver** [comment]
Fixed

**Comment by azerturk** [comment]
install Yii2 basic template and  after run php composer.phar require --prefer-dist gromver/yii2-platform-basic "*" says not found package any version so i change composer.json file minumum-stability to "dev" and run again. installation is complete. But when i go to http://localhost:8080/basic/web shows Php Compile Error again.

**Comment by gromver** [comment]
Hi, azerturk.
Did you configure the application and applied migrations? What error?

2015-01-12 16:50 GMT+04:00 azerturk notifications@github.com:

**Comment by azerturk** [comment]
Hi, yes i configure and apply migrations. But says again Php Compile Error. When i comment 22 line in MenuManager error is going but only front page show other link shows not found error.

**Comment by gromver** [comment]
The line 'use yii\web\Request;' is really unnecessary in MenuManager, but
it should not affect the work of application and cause errors. This is very
strange, I don't face such problems.
Try to update the application and post me the error message.

2015-01-12 22:42 GMT+04:00 azerturk notifications@github.com:
